### ISSUE TITLE
How to obtained cell-by-perturbation matrix using your guiderna_tool script

### ISSUE THREAD

**Issue by kaanokay** [gaofan83/single_cell_perturb_seq#2]
Hi @gaofan83,

First of all, I'd like to thank you for developing a kind of script to obtain a cell-by-perturbation matrix. I'm a newbie to Perturb-seq data analysis. I'm trying to learn Perturb-seq data analysis for my PhD project these days. I also have the same experimental design, namely we'll knock out genes using double sgRNAs per gene. I'm wondering something about your pipeline.

1) How can I obtain inputs for the guiderna_tool script? I think the guide RNA list should come from the Cell Ranger pipeline, but I have never used Cell Ranger before. So, I don't know how to start it.

2) How to obtain the cell-by-perturbation matrix from the Cell Ranger pipeline to compare it with the guiderna_tool script output?

3) Could you provide example inputs and outputs for your guiderna_tool script on GitHub?

Could you provide me with a general pipeline, including Cell Ranger and your script, for this purpose? If you answer me, I'm going to be so glad.

Best regards.

**Comment by gaofan83** [comment]
Sorry for the late response. A demo has been added to the directory https://github.com/gaofan83/single_cell_perturb_seq/tree/master/guiderna

**Comment by kaanokay** [comment]
Dear @gaofan83,

Thank you for your reply. I'll look into this demo.

Best regards.

**Comment by kaanokay** [comment]
Dear @gaofan83, hi again. Thank you for sharing this demo pipeline. Its so helpful for me. I have couple of question about this pipeline. I'm new in this field and trying to understand bioinformatics behind Perturb-seq. If you will answer me, its gonna be so helpful. 

Questions about demo pipeline:

Questions:
1) Is the data from SRA data obtained from the CRISPR library (i.e. guide RNA, SRR13587911) or data from RNA-seq?

2) Which CRISPR and RNA-seq datasets in SRA should be compared with each other? Should the knocked-out cells obtained from each CRISPR data set (guide RNA) be compared individually with each RNA-seq data set? Or is this RNA-seq data that needs to be directly countered by CRISPR data? If so, which CRISPR data should be compared to which RNA-seq data? Can you tell me the SRA accession numbers?

3) I will use CRISPR (guide RNA) fastq files for the demo pipeline you have prepared (in SRA, the assay of this data is determined as Other), but do I need to use RNA-seq data for the Cell Ranger pipeline? (They are marked as RNA-seq in the Assay section of SRA).

4) Which RNA-seq data did you use to create the scrna_barcodes.tsv file?

5) Could you please explain which data is knock or control and which is day 0, 10, and 13?I'm confused.

6) I think I need to match the cell barcodes obtained from 10X Genomics (scrna_barcodes.tsv file) with the barcodes downloaded from 10X Genomics' github (3M-february-2018.txt file). Why are we doing this? And can the 3M-february-2018.txt file be used for each CellRanger output (for scRNA-seq)? So is this file a universal file?

7) The total number of guides in guide1 and guide2 files is 47, but I got 46 log (UMI +1) vs density histogram figures. Why?

8) Should the histogram that should be obtained optimally to be able to say that the guide knocks out the cell in a good way be as shown in the demo pipeline? I also noticed that the histograms of guide1 and guide2 are different. Guide 1 contains many more positives, while Guide 2 contains fewer positives. Should I focus on both guides to find out which cells are knocked-out?

9) What do the positive and negative labels in the histogram mean? Why does the part that is zero on the x axis have the most density? Does this section represent the number of cells that do not receive guide RNAs?

10) Cont-NonTarg-1 has a dual guide RNA, but Cont-NonTarg-2 has only one guide RNA. Why?

11) There are many different guide RNA sequences for each gene, but you mentioned in the article that you used the dual guide. What is the reason for the third guide sequence? For example, Hoxa9-3 and Meis1-3?

12) As I understand it, the guide with the highest number of UMIs is the guide that knocked out the corresponding cell, and this guide is marked as 1 in the binarized file, while the other guides are marked as zero. I hope I understood it correctly.

13) I obtained two binarized files (ft_count_cap1_gd1_bin.txt and ft_count_cap2_gd2_bin.txt). Will both of these files be used when assigning cells to guides?

Thanks.
Best regards.

**Comment by kaanokay** [comment]
@gaofan83 hi again,

If we have CRISPR library that has two different lanes, for instance, EP300_CRISPR_screening_S8_L003_R1_001.fastq.gz, EP300_CRISPR_screening_S8_L003_R2_001.fastq.gz, EP300_CRISPR_screening_S8_L004_R1_001.fastq.gz, EP300_CRISPR_screening_S8_L004_R2_001.fastq.gz. Here, CRISPR library come from the same sample but it has two different lanes L003 and L004. To run your demo pipeline, I need merge those lanes for the same sample and if so, how to make this before starting your pipeline.

I'm looking forward hearing from you.
Best regards.

**Comment by gaofan83** [comment]
Sorry for the late response. Current pipeline doesn't work for gz files. You will need to use combine L003 and L004 files first using zcat file_L003.fastq.gz file_L004.fastq.gz > file_combined.fastq

**Comment by kaanokay** [comment]
Thank you so much for reply!

**Comment by kaanokay** [comment]
Hi @gaofan83,

I'm running guiderna_tool now for CRISPR library. My experimental design is some different than yours. As I see, you have gRNA1-capture1 and gRNA2-capture2 sequences and this tool is designed for such CRISPR library. My design is gRNA1 and gRNA2-capture 1, that is, I have two gudies for a vector but only one capture sequence (capture 1). I think that's reason why I got error when I used guiderna_tool for knock-out detection.

By the way, in this CRISPR library, I knock-outed only one gene. guides1.txt and guides2.txt files have only guides for one gene. Perhaps, I got error below because of that design.

How I used your tool:

$ single_cell_perturb_seq/guiderna/guiderna_tool --R1 CRISPR_screening_R1.fastq --R2 CRISPR_screening_R2.fastq --bc barcodes_perturb_guide.tsv --gd1 guides1.txt --gd2 guides2.txt

Error that I got:

thread 'main' panicked at 'index 50 out of range for slice of length 28', src/guiderna_tool.rs:167:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I wonder its possible to arrange this script for this design. If so, could you share with me? I want to use this script for my manuscript and cite you.

Bw.

**Comment by gaofan83** [comment]
can you share with me barcodes_perturb_guide.tsv, guides1.txt and guides2.txt files?

**Comment by kaanokay** [comment]
For sure,

[barcodes_perturb_guide.csv](https://github.com/gaofan83/single_cell_perturb_seq/files/9054613/barcodes_perturb_guide.csv)
[guides1.csv](https://github.com/gaofan83/single_cell_perturb_seq/files/9054614/guides1.csv)
[guides2.csv](https://github.com/gaofan83/single_cell_perturb_seq/files/9054615/guides2.csv)

**Comment by gaofan83** [comment]
Can you also share the first few records of your R1.fastq and R2.fastq files? Barcodes and guide sequences seem ok.

**Comment by kaanokay** [comment]
R1 fastq:

@A00771:656:HJVKKDSX2:3:1101:19298:1000 1:N:0:NTTTACCGCA+NACAATAAAG
NACGGTATCCCATGTACTCTGCGTTGAT
+
#:FFF:FFFFFFFFFFFFFFFFFFFFFF
@A00771:656:HJVKKDSX2:3:1101:19316:1000 1:N:0:NTTTACCGCA+NACAATAAAG
NTCTAGTGTGTCGAGAAGGCCATAGATT
+
#FFFFFFFFFFFFFFFFFFFF:FFFFFF
@A00771:656:HJVKKDSX2:3:1101:19334:1000 1:N:0:NTTTACCGCA+NACAATAAAG
NCTTCACTCCATATGATAAATGTACTTG
+
#FFFFFFFFFFFFFFFFFFFFFFFFFFF
@A00771:656:HJVKKDSX2:3:1101:20564:1000 1:N:0:NTTTACCGCA+NACAATAAAG
NACAGCCCATGTACTCTGCGTTGATACC
+
#FFFFFFFFFFFFFFFFF:FFFFFFFFF
@A00771:656:HJVKKDSX2:3:1101:20582:1000 1:N:0:NTTTACCGCA+NACAATAAAG
NTGGGAGAGCGTGTCTTGTCTTATGATA
+
#FFFFFFFFFFFFFF:FFFFFFFFFFFF
@A00771:656:HJVKKDSX2:3:1101:20745:1000 1:N:0:NTTTACCGCA+NACAATAAAG
NGACAGGCATTCCATTGACACAGATCCG

R2 fastq:

@A00771:656:HJVKKDSX2:3:1101:19298:1000 2:N:0:NTTTACCGCA+NACAATAAAG
NAGCAGTGGTATCAACGCAGAGTACATGGGATACCGTACTGTCTCTTATACACATCTGACGCTGCCGACGACTTTATTGTCGTGGTGGGC
+
#FFFFF:FFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFFFF:F,FFFFFFF,FF:FFFFFFFFFFFFFFFFF::F,::FF:F,,,,,,
@A00771:656:HJVKKDSX2:3:1101:19316:1000 2:N:0:NTTTACCGCA+NACAATAAAG
NAGCAGTGGTATCAACGCAGAGTACATGGGGGGAACCGTTCATGACTTGATGTTTCAGAGCTAAGCACAAGAGTGCATAGCAAGTTGAAA
+
#FFFFF:FFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@A00771:656:HJVKKDSX2:3:1101:19334:1000 2:N:0:NTTTACCGCA+NACAATAAAG
NAGCAGTGGTATCAACGCAGAGTACATGGGGTTTCCGTAGTGTAGTGGTCATCACGCTCACCTATTAGCGGCTAAGGCAAGTACATTTAT
+
#FFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:
@A00771:656:HJVKKDSX2:3:1101:20564:1000 2:N:0:NTTTACCGCA+NACAATAAAG
NAGCAGTGGTATCAACGCAGAGTACATGGGAAGCAGTGGTATCAACGCAGAGTACATGGGCTGTCCTGTCTCTTATACACATCTGACGCT
+
#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFF:
@A00771:656:HJVKKDSX2:3:1101:20582:1000 2:N:0:NTTTACCGCA+NACAATAAAG
NAGCAGTGGTATCAACGCAGAGTACATGGGCTACACGACGCTCTTCCGATCTATGGGAGTCCGTGTCTGTTGCTCACCTATTAGCGGCTA
+
#FFFFFF:FFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFF:FFFFF:FFF
@A00771:656:HJVKKDSX2:3:1101:20745:1000 2:N:0:NTTTACCGCA+NACAATAAAG
NAGCAGTGGTATCAACGCAGAGTACATGGGAAGCAGTGGTATCAACGCAGAGTACATGGGCTCACCTCTTAGCGGCTAAGGCGGATCTGT

Those fastq files are merged of different lanes. I merged lane1 R1 fastq file with lane2 R1 fastq file. I did the same thing for R2 fastq files.

**Comment by gaofan83** [comment]
Your R1 file is problematic without capture sequence. See https://teichlab.github.io/scg_lib_structs/data/CG000197_GuideRNA_SpecificationsCompatible_withFeatureBarcodingtechnology_forCRISPRScreening_Rev-A.pdf

**Comment by kaanokay** [comment]
I see. I'll try this pipeline again soon. Thank you so much!
